-- 颜值打分9项客观指标 V2

-- 添加新的9项指标到 beauty_scores 表
ALTER TABLE beauty_scores 
ADD COLUMN IF NOT EXISTS body_shape DECIMAL(3, 1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS symmetry DECIMAL(3, 1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS face_age DECIMAL(3, 1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS hairline DECIMAL(3, 1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS eye_bags DECIMAL(3, 1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS teeth DECIMAL(3, 1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS nose_bridge DECIMAL(3, 1) DEFAULT NULL;

-- 添加新的9项指标到 profiles 表
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS body_shape DECIMAL(3, 1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS symmetry DECIMAL(3, 1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS face_age DECIMAL(3, 1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS hairline DECIMAL(3, 1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS eye_bags DECIMAL(3, 1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS teeth DECIMAL(3, 1) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS nose_bridge DECIMAL(3, 1) DEFAULT NULL;
