// AI相亲问题库 v1.0
// 分类：Auto(自动) / Semi(半自动) / Dog(狗蛋主导)

export const questions = [
  // ========== 基础信息 (Auto) ==========
  {
    id: 'basic_1',
    type: 'auto',
    category: '基础信息',
    question: '先简单认识一下～你怎么称呼呢？',
    field: 'nickname',
    inputType: 'text',
    placeholder: '可以是昵称或名字',
  },
  {
    id: 'basic_2',
    type: 'auto',
    category: '基础信息',
    question: '你的性别是？',
    field: 'gender',
    inputType: 'choice',
    options: ['男生', '女生'],
  },
  {
    id: 'basic_3',
    type: 'auto',
    category: '基础信息',
    question: '出生年份是？',
    field: 'birthYear',
    inputType: 'number',
    placeholder: '例如：1995',
  },
  {
    id: 'basic_4',
    type: 'auto',
    category: '基础信息',
    question: '现在住在哪个城市呀？',
    field: 'city',
    inputType: 'text',
    placeholder: '例如：北京、上海',
  },
  {
    id: 'basic_5',
    type: 'auto',
    category: '基础信息',
    question: '从事什么领域的工作呢？',
    field: 'occupation',
    inputType: 'text',
    placeholder: '简单描述一下～',
  },
  {
    id: 'basic_6',
    type: 'auto',
    category: '基础信息',
    question: '学历是？',
    field: 'education',
    inputType: 'choice',
    options: ['本科', '硕士', '博士', '其他'],
  },
  {
    id: 'basic_7',
    type: 'auto',
    category: '基础信息',
    question: '能否接受异地恋？',
    field: 'acceptLongDistance',
    inputType: 'choice',
    options: ['可以', '不太能接受', '看情况'],
  },
  {
    id: 'basic_8',
    type: 'auto',
    category: '基础信息',
    question: '能接受对方比你大/小几岁？',
    field: 'ageRange',
    inputType: 'text',
    placeholder: '例如：±3岁、±5岁',
  },

  // ========== 兴趣 & 话题共鸣 (Semi) ==========
  {
    id: 'interest_1',
    type: 'semi',
    category: '兴趣爱好',
    question: '平时休息时，你更愿意「看剧/看电影」「看书/听播客」，还是「玩游戏/刷短视频」？可以说一个最近喜欢的作品吗？🌿',
    field: 'hobbyType',
    inputType: 'text',
    placeholder: '分享一个你喜欢的作品～',
    checkVague: true,
  },
  {
    id: 'interest_2',
    type: 'semi',
    category: '生活方式',
    question: '周末通常怎么过？是宅家充电、约朋友出去玩，还是独自探索城市？✨',
    field: 'weekendStyle',
    inputType: 'text',
    placeholder: '描述一下理想的周末～',
    checkVague: true,
  },
  {
    id: 'interest_3',
    type: 'semi',
    category: '长期爱好',
    question: '有什么坚持了三年以上的爱好吗？是怎么开始的呢？🌿',
    field: 'longTermHobby',
    inputType: 'text',
    placeholder: '说说你的故事～',
    checkVague: true,
  },
  {
    id: 'interest_4',
    type: 'semi',
    category: '旅行偏好',
    question: '更吸引你的旅行方式是「打卡网红地」还是「随机漫步」？上次出行去了哪？✨',
    field: 'travelStyle',
    inputType: 'text',
    placeholder: '聊聊你的旅行经历～',
  },
  {
    id: 'interest_5',
    type: 'semi',
    category: '精神享受',
    question: '听音乐、看展、逛展，哪种让你感觉"活着真不错"？🌿',
    field: 'spiritualEnjoyment',
    inputType: 'text',
    placeholder: '描述那个打动你的瞬间～',
  },
  {
    id: 'interest_6',
    type: 'semi',
    category: '近期关注',
    question: '最近有在读什么书、追什么剧、或玩什么游戏吗？什么最打动你？✨',
    field: 'recentInterest',
    inputType: 'text',
    placeholder: '分享一下～',
  },
  {
    id: 'interest_7',
    type: 'semi',
    category: '假期模式',
    question: '如果突然有三天假期，你会选择「完全躺平」还是「安排满满」？🌿',
    field: 'holidayMode',
    inputType: 'choice',
    options: ['完全躺平', '安排满满', '中间状态'],
  },
  {
    id: 'interest_8',
    type: 'semi',
    category: '独特爱好',
    question: '有什么小众爱好或奇怪的收集癖吗？✨',
    field: 'uniqueHobby',
    inputType: 'text',
    placeholder: '说说看～（没有也可以直说）',
  },
  {
    id: 'interest_9',
    type: 'semi',
    category: '社交角色',
    question: '朋友聚会时，你通常是「气氛组」「旁听者」还是「组织者」？🌿',
    field: 'socialRole',
    inputType: 'choice',
    options: ['气氛组', '旁听者', '组织者', '视情况而定'],
  },

  // ========== 生活底色 (Auto + Semi) ==========
  {
    id: 'life_1',
    type: 'semi',
    category: '消费观念',
    question: '你的消费观更接近「攒钱有安全感」「平衡享受当下」还是「喜欢就买」？',
    field: 'spendingHabit',
    inputType: 'choice',
    options: ['攒钱有安全感', '平衡享受当下', '喜欢就买'],
  },
  {
    id: 'life_2',
    type: 'auto',
    category: '作息类型',
    question: '作息是「早睡早起规律党」「夜猫子」还是「看情况灵活调整」？',
    field: 'sleepSchedule',
    inputType: 'choice',
    options: ['早睡早起', '夜猫子', '灵活调整'],
  },
  {
    id: 'life_3',
    type: 'auto',
    category: '整洁程度',
    question: '家里/房间通常是「井井有条」「乱中有序」还是「能找着就行」？',
    field: 'tidiness',
    inputType: 'choice',
    options: ['井井有条', '乱中有序', '能找着就行'],
  },
  {
    id: 'life_4',
    type: 'semi',
    category: '压力应对',
    question: '遇到压力时，你倾向「自己消化」「找人倾诉」还是「转移注意力」？',
    field: 'stressResponse',
    inputType: 'choice',
    options: ['自己消化', '找人倾诉', '转移注意力'],
  },
  {
    id: 'life_5',
    type: 'semi',
    category: '决策方式',
    question: '做决定时，你更相信「直觉感受」「逻辑分析」还是「问信任的人」？',
    field: 'decisionStyle',
    inputType: 'choice',
    options: ['直觉感受', '逻辑分析', '问信任的人'],
  },
  {
    id: 'life_6',
    type: 'dog',
    category: '家庭关系',
    question: '和家人/原生家庭的关系，用一个词形容是什么？',
    field: 'familyRelationship',
    inputType: 'text',
    placeholder: '一个词，真实的就好',
    needDeepDive: true,
  },
  {
    id: 'life_7',
    type: 'auto',
    category: '计划性',
    question: '你觉得自己是「计划控」「随性派」还是「大方向有计划，细节随意」？',
    field: 'planningStyle',
    inputType: 'choice',
    options: ['计划控', '随性派', '大方向有计划'],
  },
  {
    id: 'life_8',
    type: 'semi',
    category: '成就感来源',
    question: '工作中/学业上，什么状态会让你感到满足？',
    field: 'achievementSource',
    inputType: 'text',
    placeholder: '完成任务、被认可、解决难题...？',
  },
  {
    id: 'life_9',
    type: 'semi',
    category: '独处感受',
    question: '独处时，你会感到「充电回血」「有点无聊」还是「偶尔孤独但享受」？',
    field: 'solitudeFeeling',
    inputType: 'choice',
    options: ['充电回血', '有点无聊', '偶尔孤独但享受'],
  },
  {
    id: 'life_10',
    type: 'semi',
    category: '生活偏好',
    question: '如果必须选，你更想要「稳定可预期的生活」还是「充满变化的可能性」？',
    field: 'lifePreference',
    inputType: 'choice',
    options: ['稳定可预期', '充满变化'],
  },

  // ========== 核心人格 (Dog) ==========
  {
    id: 'core_1',
    type: 'dog',
    category: '当前状态',
    question: '形容一下你现在的状态——是「正在找方向」「稳步前进」还是「想要突破」？不用着急，慢慢想～',
    field: 'currentState',
    inputType: 'text',
    placeholder: '真实的感受就好',
    needDeepDive: true,
  },
  {
    id: 'core_2',
    type: 'dog',
    category: '信任点',
    question: '你觉得朋友最信任你哪一点？举个例子。慢慢想，真实的就好～',
    field: 'trustedFor',
    inputType: 'text',
    placeholder: '具体例子比形容词更重要',
    needDeepDive: true,
  },
  {
    id: 'core_3',
    type: 'dog',
    category: '被理解经历',
    question: '上一次感到"被深深理解"是什么时候？什么事？不用着急，慢慢想～',
    field: 'understoodMoment',
    inputType: 'text',
    placeholder: '如果想不到也可以直说',
    needDeepDive: true,
  },
  {
    id: 'core_4',
    type: 'dog',
    category: '关系盲点',
    question: '你觉得自己在亲密关系中，最可能犯的"毛病"是什么？（比如爱冷战、太黏人、藏心事）',
    field: 'relationshipBlindspot',
    inputType: 'text',
    placeholder: '诚实的自我观察',
    needDeepDive: true,
  },
  {
    id: 'core_5',
    type: 'dog',
    category: '理想关系',
    question: '用三个词形容你理想中的亲密关系，会是什么？不用着急，慢慢想～',
    field: 'idealRelationship',
    inputType: 'text',
    placeholder: '三个词，可以简单解释',
    needDeepDive: true,
  },

  // ========== 相处偏好 (Dog) ==========
  {
    id: 'relationship_1',
    type: 'dog',
    category: '核心需求',
    question: '恋爱中，你最需要对方给什么？（被肯定、陪伴、空间、被照顾……）',
    field: 'coreNeed',
    inputType: 'text',
    placeholder: '最重要的那个需求',
    needDeepDive: true,
  },
  {
    id: 'relationship_2',
    type: 'dog',
    category: '冲突处理',
    question: '吵架/有分歧时，你希望对方怎么对你？（给时间冷静、马上沟通、先道歉再聊……）',
    field: 'conflictHandling',
    inputType: 'text',
    placeholder: '你真实的偏好',
    needDeepDive: true,
  },
  {
    id: 'relationship_3',
    type: 'auto',
    category: '联系频率',
    question: '你能接受的"最频繁联系"是什么样的？',
    field: 'contactFrequency',
    inputType: 'choice',
    options: ['每天聊', '有事才找', '住一起各自忙碌', '看情况'],
  },
  {
    id: 'relationship_4',
    type: 'dog',
    category: '关系红线',
    question: '对方有什么行为是你绝对接受不了的？（说谎、冷暴力、控制欲、不上进……说1-3个）',
    field: 'dealBreakers',
    inputType: 'text',
    placeholder: '你的底线',
    needDeepDive: true,
  },
  {
    id: 'relationship_5',
    type: 'dog',
    category: '未来画面',
    question: '想象一年后，你和理想伴侣的生活画面是什么样的？（不用完美，真实就好）',
    field: 'futureVision',
    inputType: 'text',
    placeholder: '描述那个画面～',
    needDeepDive: true,
  },
];

// 获取问题总数
export const getTotalQuestions = () => questions.length;

// 按分类获取问题
export const getQuestionsByType = (type) => questions.filter(q => q.type === type);

// 获取当前问题索引
export const getQuestionIndex = (id) => questions.findIndex(q => q.id === id);

// 获取下一个问题
export const getNextQuestion = (currentId) => {
  const currentIndex = getQuestionIndex(currentId);
  return questions[currentIndex + 1] || null;
};